Новожилов Дмитрий. Задание 1
h31/NetworksLab2019HSE pull request #1
Opened 2019-02-04 21:47 UTC by demiurg906

В данной представлены клиенты и серверы для заданий [3 (почта)](https://github.com/demiurg906/NetworksLab2019HSE/tree/task-1/EmailClientServer) и [17 (вакансии)](https://github.com/demiurg906/NetworksLab2019HSE/tree/task-1/VacancyClientServer)

2019-02-11 19:08 UTC, h31 requested changes

2019-02-11 19:08 UTC, h31 commented on EmailClientServer/server/src/Server.cpp
> +    if (setsockopt(serverSocket, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(opt))) {
По каким причинам вы решили включить `SO_REUSEPORT`?

2019-02-11 19:08 UTC, h31 commented on EmailClientServer/server/src/Server.cpp
> +            continue;
Если `accept` будет выдавать ошибку, то мы попадем в бесконечный цикл?
![image](https://user-images.githubusercontent.com/3375923/52583472-c3d7df80-2e40-11e9-88db-27437c4c640f.png)

2019-02-11 19:08 UTC, h31 commented on EmailClientServer/server/src/Server.cpp
> +        sockets.insert(clientSocket);
А где-нибудь сокеты удаляются из списка? Я не нашёл. Не очень критичная, но всё же утечка памяти.

Кроме того, можно заменить `std::set` на `std::unordered_set`.

2019-02-11 19:08 UTC, h31 commented on EmailClientServer/common/src/serialization/size_collector.cpp
> +    return ResponseBodySizeCollector(&response.getResponseBody()).getSize() + 1; // + status
Не очень понятно, почему `+ 1`, если в response.cpp:9 к размеру сообщения уже прибавляется `INT_SIZE`.

2019-02-11 19:08 UTC, h31 commented on VacancyClientServer/client/src/main.cpp
> +    cout << "Enter server address (blank for 127.0.0.1) :> ";
Обычно в клиентах имеется возможность переопределить порт сервера. Как минимум, в тексте задания требуется такая возможность.

2019-02-11 19:08 UTC, h31 commented on VacancyClientServer/client/src/Client.cpp
> +    std::string hello = "Hello from client ";
Лишняя строчка.

2019-02-11 19:08 UTC, h31 commented on VacancyClientServer/client/src/Client.cpp
> +            socket = openSocket();
Для каждой введенной команды открывается отдельное соединение к серверу. Можете аргументировать, почему было принято организовать сетевой обмен именно таким образом?

2019-02-11 19:08 UTC, h31 commented on VacancyClientServer/client/src/Client.cpp
> +    auto response = communicate(socket, request);
Вызов `communicate` (работа с сетью) и работа с JSON-ом дублируется в каждом варианте вызова `execute`. Можно ли как-нибудь вынести общий код в отдельный метод/функцию?

2019-02-11 19:08 UTC, h31 commented on VacancyClientServer/client/src/Client.cpp
> +    json request;
В одном методе находится и обработка пользовательского ввода, и работа с сетью. Это разные зоны ответственности, и поэтому есть смысл перераспределить код по методам. Касается не только этого метода.

2019-02-11 19:08 UTC, h31 commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.13)
Когда два несвязанных проекта имеют один общий сценарий сборки, это несколько запутывает. Лично мне более привычно, когда каждый проект имеет отдельный сборочный скрипт. В задании не было сказано про оформление сборки, так что можете не исправлять это замечание.

2019-02-11 19:08 UTC, h31 commented on EmailClientServer/server/src/Server.cpp
> +        cout << "Client " << clientId << " connected" << endl;
Подобные сообщения желательно при необходимости отключать (используя одну из систем логгирования или написав свою).

2019-02-11 19:14 UTC, h31 commented
Почему-то не заработало получение писем. Исправьте, пожалуйста. И да, `not found`.
![image](https://user-images.githubusercontent.com/3375923/52587039-0fdb5200-2e4a-11e9-8b56-bb55286c4a32.png)

А в целом мне проект понравился. Всё сделано акккуратно. Использование visitor-ов для обработки структур - интересная идея.

2019-02-11 19:45 UTC, h31 commented on EmailClientServer/common/src/communication/communication.cpp
> +    readToBuffer(socket, buffer.get(), messageSize);
Что произойдет, если `read` вернет только часть сообщения?

2019-02-11 19:47 UTC, h31 commented on EmailClientServer/server/include/EmailWithInfo.h
> +class EmailWithInfo {
Старайтесь не использовать общих слов, таких как `Info`, в названии классов и других объектов программы. Они не привносят дополнительных знаний о том, зачем нужен класс. Замените Info на что-то более конкретное.

2019-02-11 19:53 UTC, demiurg906 commented on EmailClientServer/server/src/Server.cpp
> +    if (setsockopt(serverSocket, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(opt))) {
Взял с примера

2019-02-11 19:57 UTC, demiurg906 commented on EmailClientServer/server/src/Server.cpp
> +            continue;
Ну, сервер и так живёт в бесконечном цикле
На мой взгляд, прерывать сервер нельзя, т.к. соединение было не установлено из-за того, что умер клиент, а не сеть сервера (по error кодам, сколь я понял, у кого отвалилась сеть понять нельзя)

2019-02-11 20:01 UTC, demiurg906 commented on EmailClientServer/server/src/Server.cpp
> +        sockets.insert(clientSocket);
Как вы ниже верно заметили, это не список, а множество. Так что сверху оно ограничено интом (и нет, не удаляется, т.к. на плюсах я не нашёл удобных потокобезопасных коллекций, поддерживающих удаление)

А можно и не заменять, для хранения интов особой разницы нет

2019-02-11 20:02 UTC, demiurg906 commented on EmailClientServer/common/src/serialization/size_collector.cpp
> +    return ResponseBodySizeCollector(&response.getResponseBody()).getSize() + 1; // + status
Ещё один байт -- это статус ответа. Там даже комментарий есть

2019-02-11 20:06 UTC, demiurg906 commented on VacancyClientServer/client/src/Client.cpp
> +            socket = openSocket();
Я пошёл по пути наименьшего сопротивления. Такую схему проще всего реализовать, не надо поддерживать кучу подключений. Можно ещё сказать обоснованную причину, что, мол, при такой схеме один сервер сможет работать больше чем c 65k клиентов "одновременно" (обработка одного клиента быстрая, так что порты освобождаются также быстро).
Если бы я писал серьёзное приложение с большей функциональностью, то, если того требуют условия системы, я бы написал поддержку постоянного соединения, но всё это было бы на другом стеке технологий, которые больше располагают к удобному написанию сетевых сервисов (JVM)

2019-02-11 20:12 UTC, demiurg906 commented on VacancyClientServer/client/src/Client.cpp
> +    auto response = communicate(socket, request);
Не думаю, т.к. в каждой комманде формируются достаточно разные запросы (с разным набором и количеством полей разных типов), а с учётом того, что подобного кода здесь немного, то воротить какую-то общую шаблонную магию, которая лишь слегка уменьшит количество кода достаточно бессмысленно

2019-02-11 20:17 UTC, demiurg906 commented on EmailClientServer/common/src/communication/communication.cpp
> +    readToBuffer(socket, buffer.get(), messageSize);
Такого произойти не может, это блокирующий `read` (смотри [документацию](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.bpxbd00/rtrea.htm))

2019-02-11 20:43 UTC, demiurg906 commented
@h31 Замечания пофиксил

2019-02-12 14:22 UTC, h31 commented on EmailClientServer/server/src/Server.cpp
> +    if (setsockopt(serverSocket, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(opt))) {
Перед тем, как переносить код в проект, нужно в нем разобраться. Особенно если речь об учебном проекте, а код связан непосредственно с предметом изучения.

2019-02-12 14:26 UTC, h31 commented on EmailClientServer/server/src/Server.cpp
> +            continue;
Я просто нажал Ctrl-C. Обработчик сигнала закрыл все сокеты, включая серверный. `accept` выдает ошибку при попытке использования закрытого сокета. После этого программа никак не реагирует на Ctrl-C, остановить её можно только с помощью `kill -9`. Очевидно, программа не должна так завершаться. Никакого обмена данных с клиентами в тот момент не было.

2019-02-12 14:29 UTC, h31 commented on EmailClientServer/server/src/Server.cpp
> +        sockets.insert(clientSocket);
`set` - это бинарное дерево поиска, `unordered_set` - это хэш-таблица. 
> unordered_set containers are faster than set containers to access individual elements by their key,

Но ОК, сейчас обращений по ключу нет, да и замечание не очень существенное. Скорее FYI.

2019-02-12 14:31 UTC, h31 commented on VacancyClientServer/client/src/Client.cpp
> +            socket = openSocket();
> Можно ещё сказать обоснованную причину, что, мол, при такой схеме один сервер сможет работать больше чем c 65k клиентов "одновременно" (обработка одного клиента быстрая, так что порты освобождаются также быстро).

Чем обусловлено ограничение в 65к клиентов? (не считая тестового варианта, когда все клиенты запускаются на одной машине).

2019-02-12 14:40 UTC, demiurg906 commented on EmailClientServer/server/src/Server.cpp
> +            continue;
А, проблема здесь была.
Пофиксил

2019-03-05 08:45 UTC, h31 commented
Принято, оценка 9.

2019-03-05 08:45 UTC, closed without merging